package config

var DefaultStyleProps = map[string]string{
	"page_width":                    "520px",
	"page_height":                   "calc(100% - 16pt - 58pt)",
	"page_top":                      "12pt",
	"page_bottom":                   "58pt",
	"page_shadow":                   "none",
	"page_justify":                  "flex-start",
	"page_align":                    "center",
	"page_font_stack":               "Inter, Arial, Helvetica, sans-serif",
	"page_background_color":         "#FFFFFF",
	"page_background_image":         "none",
	"page_foreground_color":         "#000000",
	"page_scroll_size":              "6pt",
	"page_scroll_color":             "auto",
	"page_scroll_active_color":      "auto",
	"page_user_avatar_image_width":  "71.4pt",
	"page_user_avatar_image_height": "71.4pt",
	"page_user_avatar_image_radius": "50%",
	"page_social_icon_width":        "20pt",
	"page_social_icon_height":       "20pt",
	"page_social_icon_gap":          "1pt",
	"page_social_icon_color":        "inherit",
	"page_link_gap":                 "10pt",
	"page_link_width":               "100%",
	"page_link_radius":              "5pt",
	"page_link_background_color":    "transparent",
	"page_link_background_image":    "none",
	"page_link_foreground_color":    "inherit",
	"page_link_border":              "1px solid #DDDDDD",
	"page_link_shadow":              "0 8px 12px rgb(0 0 0 / 30%)",
}
