package config

import "github.com/rajatxs/go-iamone/models"

var SocialPlatforms = map[string]models.SocialPlatform{
	"iamone": {
		Key:         "iamone",
		Type:        "username",
		Name:        "iamone",
		Hint:        "iamone username",
		Hostname:    "iamone.link",
		TemplateUrl: "https://iamone.link/{{slug}}",
	},
	"email": {
		Key:         "email",
		Type:        "email",
		Name:        "Email",
		Hint:        "your@domain.com",
		Hostname:    "",
		TemplateUrl: "mailto:{{slug}}",
	},
	"facebook": {
		Key:         "facebook",
		Type:        "url",
		Name:        "Facebook",
		Hint:        "Facebook page URL",
		Hostname:    "facebook.com",
		TemplateUrl: "{{slug}}",
	},
	"twitter": {
		Key:         "twitter",
		Type:        "username",
		Name:        "Twitter",
		Hint:        "Twitter username",
		Hostname:    "twitter.com",
		TemplateUrl: "https://twitter.com/{{slug}}",
	},
	"instagram": {
		Key:         "instagram",
		Type:        "username",
		Name:        "Instagram",
		Hint:        "Instagram username",
		Hostname:    "instagram.com",
		TemplateUrl: "https://www.instagram.com/{{slug}}",
	},
	"youtube": {
		Key:         "youtube",
		Type:        "url",
		Name:        "YouTube",
		Hint:        "YouTube channel URL",
		Hostname:    "youtube.com",
		TemplateUrl: "{{slug}}",
	},
	"tiktok": {
		Key:         "tiktok",
		Type:        "username",
		Name:        "TikTok",
		Hint:        "TikTok username",
		Hostname:    "tiktok.com",
		TemplateUrl: "https://tiktok.com/@{{slug}}",
	},
	"spotify": {
		Key:         "spotify",
		Type:        "url",
		Name:        "Spotify",
		Hint:        "Spotify page URL",
		Hostname:    "spotify.com",
		TemplateUrl: "{{slug}}",
	},
	"github": {
		Key:         "github",
		Type:        "username",
		Name:        "GitHub",
		Hint:        "GitHub username",
		Hostname:    "github.com",
		TemplateUrl: "https://github.com/{{slug}}",
	},
	"behance": {
		Key:         "behance",
		Type:        "username",
		Name:        "Behance",
		Hint:        "Behance username",
		Hostname:    "behance.net",
		TemplateUrl: "https://behance.net/{{slug}}",
	},
	"dribbble": {
		Key:         "dribbble",
		Type:        "username",
		Name:        "Dribbble",
		Hint:        "Dribbble username",
		Hostname:    "dribbble.com",
		TemplateUrl: "https://dribbble.com/{{slug}}",
	},
	"discord": {
		Key:         "discord",
		Type:        "username",
		Name:        "Discord",
		Hint:        "Discord username",
		Hostname:    "discord.com",
		TemplateUrl: "https://discord.com/invite/{{slug}}",
	},
	"medium": {
		Key:         "medium",
		Type:        "username",
		Name:        "Medium",
		Hint:        "Medium username",
		Hostname:    "medium.com",
		TemplateUrl: "https://medium.com/@{{slug}}",
	},
	"reddit": {
		Key:         "reddit",
		Type:        "username",
		Name:        "Reddit",
		Hint:        "Reddit username",
		Hostname:    "reddit.com",
		TemplateUrl: "https://reddit.com/u/{{slug}}",
	},
	"soundcloud": {
		Key:         "soundcloud",
		Type:        "username",
		Name:        "SoundCloud",
		Hint:        "SoundCloud username",
		Hostname:    "soundcloud.com",
		TemplateUrl: "https://soundcloud.com/{{slug}}",
	},
	"linkedin": {
		Key:         "linkedin",
		Type:        "url",
		Name:        "LinkedIn",
		Hint:        "LinkedIn page URL",
		Hostname:    "linkedin.com",
		TemplateUrl: "{{slug}}",
	},
	"telegram": {
		Key:         "telegram",
		Type:        "username",
		Name:        "Telegram",
		Hint:        "Telegram username",
		Hostname:    "t.me",
		TemplateUrl: "https://t.me/{{slug}}",
	},
	"patreon": {
		Key:         "patreon",
		Type:        "username",
		Name:        "Patreon",
		Hint:        "Patreon username",
		Hostname:    "patreon.com",
		TemplateUrl: "https://www.patreon.com/{{slug}}",
	},
	"pinterest": {
		Key:         "pinterest",
		Type:        "username",
		Name:        "Pinterest",
		Hint:        "Pinterest username",
		Hostname:    "pinterest.com",
		TemplateUrl: "https://www.pinterest.com/{{slug}}",
	},
	"apple-music": {
		Key:         "apple-music",
		Type:        "url",
		Name:        "Apple Music",
		Hint:        "Apple Music page URL",
		Hostname:    "music.apple.com",
		TemplateUrl: "{{slug}}",
	},
	"snapchat": {
		Key:         "snapchat",
		Type:        "username",
		Name:        "Snapchat",
		Hint:        "Snapchat username",
		Hostname:    "snapchat.com",
		TemplateUrl: "https://www.snapchat.com/add/{{slug}}",
	},
	"whatsapp": {
		Key:         "whatsapp",
		Type:        "phone",
		Name:        "WhatsApp",
		Hint:        "+00000000000 (WhatsApp)",
		Hostname:    "whatsapp.com",
		TemplateUrl: "https://api.whatsapp.com/send?phone={{slug}}",
	},
}
